// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Messages
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

// Employees
export const EMPLOYEES_REQUEST_SUCCESS = 'EMPLOYEES_REQUEST_SUCCESS';
export const EMPLOYEES_REQUEST_FAIL = 'EMPLOYEES_REQUEST_FAIL';

export const EMPLOYEES_ADD_SUCCESS = 'EMPLOYEES_ADD_SUCCESS';
export const EMPLOYEES_ADD_FAIL = 'EMPLOYEES_ADD_FAIL';

export const EMPLOYEES_EDIT_SUCCESS = 'EMPLOYEES_EDIT_SUCCESS';
export const EMPLOYEES_EDIT_FAIL = 'EMPLOYEES_EDIT_FAIL';

export const EMPLOYEES_DELETE_SUCCESS = 'EMPLOYEES_DELETE_SUCCESS';
export const EMPLOYEES_DELETE_FAIL = 'EMPLOYEES_DELETE_FAIL';

export const EMPLOYEES_REVIEW_SUCCESS = 'EMPLOYEES_REVIEW_SUCCESS';
export const EMPLOYEES_REVIEW_FAIL = 'EMPLOYEES_REVIEW_FAIL';
